

on:
  schedule:
      - cron: "5 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run the script.
      run: |
        python scripts/use_duolingo_module.py -u $DUO_USERNAME -f $HF_TOKEN -j $JWT_TOKEN
      env:
        DUO_USERNAME: ${{ secrets.DUO_USERNAME }}
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        JWT_TOKEN: ${{ secrets.JWT_TOKEN }}
